# Generated by Django 3.2.22 on 2023-10-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_vote', '0003_alter_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
    ]
