# Generated by Django 3.2.22 on 2023-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
